### ISSUE TITLE
Apple Silicon under Rosetta

### ISSUE THREAD

**Issue by asiliuk** [mattgallagher/CwlPreconditionTesting#26]
Looks like assertion is still raised if run on M1 under Rosetta. This could happen if target simulator is less then iOS 13.7 or by checking "Open with Rosetta" on Xcode app.

<img width="1050" alt="image showing EXC_BAD_INSTRUCTION" src="https://user-images.githubusercontent.com/1136316/152677127-f1cca9cd-1bc0-44cb-99f4-f6c4c5cf0064.png">

I have too little knowledge to try and fix it myself, is it even possible to address? It compiles sources with `x86_64` architecture and I'm not sure how to differentiate *Intel* vs *Apple Silicon*

Maybe you have any suggestions where to start? 
Thank you!

**Comment by Veeit** [comment]
I have the same problem, would love to see a solution

**Comment by mattgallagher** [comment]
Sorry to take so long to comment on this issue. As far as I can tell, this is an issue with lldb on Rosetta, not with the code itself – lldb always interferes and stop the execution when the bad exception is raised, despite the handler being in-place and the code working correctly.

To move past this, you must run these tests without debugging the executable. i.e. with the "Debug executable" unchecked in the scheme's "Test" settings:

![Image 2-4-2023 at 16 27](https://user-images.githubusercontent.com/28080/229336365-3846de82-c8c7-495c-8ade-c9566aa9ce5b.jpg)
