### ISSUE TITLE
Update versions of CWLPreconditionTesting in Cocoapods

### ISSUE THREAD

**Issue by younata** [mattgallagher/CwlPreconditionTesting#36]
Cocoapods has only up to 2.1.0. As of this issue, the latest version is 2.2.0.

Thanks!

![Screenshot 2024-01-17 at 6 57 00 PM](https://github.com/mattgallagher/CwlPreconditionTesting/assets/285321/21478608-fbce-418f-ae52-8952f5f4f549)

**Comment by mattgallagher** [comment]
The only difference in 2.2.0 is visionOS support. Unfortunately, the latest Cocoapods still refuses to lint podspec files containing visionOS deployment targets so things remain a little blocked.

https://github.com/CocoaPods/CocoaPods/issues/12118

**Comment by stonko1994** [comment]
[Cocoapods 1.15.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0) is available now which should enable releasing with visionOS support.

**Comment by mattgallagher** [comment]
@stonko1994 Excellent. Thanks for letting me know. I'll push this when I get home.

**Comment by younata** [comment]
@mattgallagher I just wanted to remind you to push this, as cocoapods.org still has the older versions of CWLPreconditionTesting.

**Comment by mattgallagher** [comment]
Finally done. Sorry for the delay.
