### ISSUE TITLE
Xcode 16 Build Warnings

### ISSUE THREAD

**Issue by LowAmmo** [mattgallagher/CwlPreconditionTesting#38]
Getting some build warnings when building CwlPreconditionTesting

     Pods/CwlPreconditionTesting/Sources/CwlPreconditionTesting/CwlBadInstructionException.swift:35:14: warning: class 'BadInstructionException' must restate inherited '@unchecked Sendable' conformance
     public class BadInstructionException: NSException {
                  ^

I can try to put together a Pull Request to fix this...but might be a few days.

Just trying to eliminate all build warnings - doesn't seem to currently cause any real issues when building with the current Xcode 16 Beta (Beta 5).

**Comment by mattgallagher** [comment]
Merged

**Comment by LowAmmo** [comment]
Thanks, @mattgallagher !
